admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"